# Generated by Django 5.0.6 on 2024-09-15 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schema_generator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdatabase",
            name="domain",
            field=models.CharField(default="General", max_length=50),
        ),
    ]
