# Generated by Django 5.0.6 on 2024-09-26 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schema_generator", "0002_userdatabase_domain"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userdatabase",
            name="name",
        ),
        migrations.AddField(
            model_name="userdatabase",
            name="ai_enhanced_schema",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userdatabase",
            name="ai_suggestions",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userdatabase",
            name="missing_columns",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userdatabase",
            name="missing_tables",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userdatabase",
            name="original_schema",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userdatabase",
            name="warehouse_schema",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userdatabase",
            name="domain",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
